"""
Django settings for Mangement project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Web/Management/settings.py

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = True  # Keep this as True for development
ALLOWED_HOSTS = []

ROOT_URLCONF = 'Management.urls'  # <--- ADD THIS LINE HERE

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        # <-- This line was missing or incorrect
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',       # <-- This defines the database file
    }
}

# ... (like INSTALLED_APPS, MIDDLEWARE, etc.) ...

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # <-- ADD THIS LINE to point to your new 'templates' folder
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # This tells Django to look for templates in app-specific 'templates' directories
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ... (STATIC_URL and STATICFILES_DIRS) ...

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    # This should still point to your 'static' folder for CSS/JS
    os.path.join(BASE_DIR, 'static'),
]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # Ensure this is here
    'rest_framework',
    'rest_framework.authtoken',   # Add this for token authentication
    'corsheaders',                # Add this for CORS
    'management',                 # Your app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Add this right after SessionMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ... (rest of your settings) ...

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Add a directory where Django will look for static files for your frontend
STATICFILES_DIRS = [
    # This tells Django to look in your project's 'static' folder
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF settings (already there, just confirming)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Add TokenAuthentication
        # Keep SessionAuthentication for browsable API
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    # Add your Codespaces URL here if it's different and you're serving the frontend separately
    # e.g., "https://your-codespaces-url.github.dev",
]
# Or, for development convenience (less secure for production):
# Set to False in production and use CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = True

# If using CORS_ALLOW_ALL_ORIGINS = True, you might not need CORS_ALLOWED_ORIGIN
# But it's good to have them if you switch to False
